---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.3.2
  hooks:
    - id: check-github-workflows
