reproduce:
    -rm doc.txt old.doc.txt
    pip-compile -q --strip-extras doc.in -o doc.txt
    cp doc.txt old.doc.txt
    pip-compile -q --strip-extras doc.in -o doc.txt
    -diff doc.txt old.doc.txt

solution:
    -rm doc.txt old.doc.txt
    pip-compile -q --strip-extras doc.in -o doc.txt
    mv doc.txt old.doc.txt
    PIP_CONSTRAINT=old.doc.txt pip-compile -q --strip-extras doc.in -o doc.txt
    -diff doc.txt old.doc.txt
