name: build
on:
  push:

jobs:
  check_mypy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        py: [3.7, 3.8, 3.9]
    name: "Check mypy on ${{ matrix.os }} py${{  matrix.py }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: install
        run: |
          python -m pip install -U pip setuptools
          python -m pip install mypy
      - name: run
        run: ./mypy-issues/run.sh
